# Generated by Django 4.1.7 on 2023-03-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_to',
            field=models.CharField(default='SOME STRING', max_length=40),
        ),
        migrations.AlterField(
            model_name='project',
            name='enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='startdate',
            field=models.DateField(),
        ),
    ]
